In [4]:
import pandas as pd

df = pd.read_csv("../data/processed/pl_matches_all.csv")
df.head()

,date,season,home_team,away_team,home_goals,away_goals,result,home_goals_ht,away_goals_ht,home_shots,away_shots,home_shots_ot,away_shots_ot,home_corners,away_corners,referee
0,2020-09-12,2020-2021,Fulham,Arsenal,0,3,AWAY_TEAM,0,1,5,13,2,6,2,3,C Kavanagh
1,2020-09-12,2020-2021,Crystal Palace,Southampton,1,0,HOME_TEAM,1,0,5,9,3,5,7,3,J Moss
2,2020-09-12,2020-2021,Liverpool,Leeds,4,3,HOME_TEAM,3,2,22,6,6,3,9,0,M Oliver
3,2020-09-12,2020-2021,West Ham,Newcastle,0,2,AWAY_TEAM,0,0,15,15,3,2,8,7,S Attwell
4,2020-09-13,2020-2021,West Brom,Leicester,0,3,AWAY_TEAM,0,0,7,13,1,7,2,5,A Taylor

In [14]:
rows, columns = df.shape
print(f"rows: {rows}\ncolumns: {columns}")

rows: 2171
columns: 16

In [17]:
for header in list(df.columns.values): print(header)

date
season
home_team
away_team
home_goals
away_goals
result
home_goals_ht
away_goals_ht
home_shots
away_shots
home_shots_ot
away_shots_ot
home_corners
away_corners
referee

In [21]:
print(df.dtypes
)

date               str
season             str
home_team          str
away_team          str
home_goals       int64
away_goals       int64
result             str
home_goals_ht    int64
away_goals_ht    int64
home_shots       int64
away_shots       int64
home_shots_ot    int64
away_shots_ot    int64
home_corners     int64
away_corners     int64
referee            str
dtype: object

In [22]:
missing = df.isnull().sum()
print(missing)

date             0
season           0
home_team        0
away_team        0
home_goals       0
away_goals       0
result           0
home_goals_ht    0
away_goals_ht    0
home_shots       0
away_shots       0
home_shots_ot    0
away_shots_ot    0
home_corners     0
away_corners     0
referee          0
dtype: int64

In [23]:
df.describe()

,home_goals,away_goals,home_goals_ht,away_goals_ht,home_shots,away_shots,home_shots_ot,away_shots_ot,home_corners,away_corners
count,2171.000000,2171.000000,2171.000000,2171.000000,2171.000000,2171.000000,2171.000000,2171.000000,2171.000000,2171.000000
mean,1.556426,1.339475,0.715799,0.585444,13.903270,11.666053,4.821281,4.122524,5.624136,4.684938
std,1.328149,1.220185,0.849410,0.795407,5.695567,5.157469,2.588939,2.368126,3.064536,2.818839
min,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,10.000000,8.000000,3.000000,2.000000,3.000000,3.000000
50%,1.000000,1.000000,1.000000,0.000000,13.000000,11.000000,5.000000,4.000000,5.000000,4.000000
75%,2.000000,2.000000,1.000000,1.000000,17.000000,15.000000,6.000000,5.000000,8.000000,6.000000
max,9.000000,8.000000,5.000000,5.000000,36.000000,37.000000,16.000000,15.000000,17.000000,19.000000

In [27]:
results = list(df["result"])
home_wins = 0
away_wins = 0
draws = 0

for result in results:
    if result == "HOME_TEAM":
        home_wins += 1
    elif result == "DRAW":
        draws += 1
    else:
        away_wins += 1

print(f"Home wins: {home_wins}\nAway Wins: {away_wins}\nDraws: {draws}")

Home wins: 935
Away Wins: 730
Draws: 506

In [28]:
df["result"].value_counts()

result
HOME_TEAM    935
AWAY_TEAM    730
DRAW         506
Name: count, dtype: int64

In [6]:
from match_predictor.features import build_features

new_df=build_features(df)

new_df.tail()

,date,home_team,away_team,ht_avg_gs,at_avg_gs,ht_avg_gc,at_avg_gc,ht_home_form,at_away_form,ht_overall_form,at_overall_form,result
2166,2026-02-22,Sunderland,Fulham,1.2,1.0,1.6,2.0,8,4,6,3,AWAY_TEAM
2167,2026-02-22,Tottenham,Arsenal,1.2,2.4,2.0,1.2,2,9,2,8,AWAY_TEAM
2168,2026-02-22,Crystal Palace,Wolves,1.2,0.6,1.8,1.8,2,3,4,2,HOME_TEAM
2169,2026-02-22,Nott'm Forest,Liverpool,0.8,1.8,0.8,1.4,3,8,6,7,AWAY_TEAM
2170,2026-02-23,Everton,Man United,1.2,2.2,1.0,1.0,2,6,8,13,AWAY_TEAM